-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DimStation"
(

    CONSTRAINT "DimStation_pkey" PRIMARY KEY (station_id)
);

CREATE TABLE IF NOT EXISTS public."DimTruck"
(

    CONSTRAINT "DimTruck_pkey" PRIMARY KEY (truck_id)
);

CREATE TABLE IF NOT EXISTS public."FactTrips"
(

    CONSTRAINT "FactTrips_pkey" PRIMARY KEY (trip_id)
);

CREATE TABLE IF NOT EXISTS public."MyDimDate"
(

    CONSTRAINT "MyDimDate_pkey" PRIMARY KEY (date_id)
);

ALTER TABLE IF EXISTS public."FactTrips"
    ADD CONSTRAINT date_id FOREIGN KEY (date_id)
    REFERENCES public."MyDimDate" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."FactTrips"
    ADD CONSTRAINT station_id FOREIGN KEY (station_id)
    REFERENCES public."DimStation" (station_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."FactTrips"
    ADD CONSTRAINT truck_id FOREIGN KEY (truck_id)
    REFERENCES public."DimTruck" (truck_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;